# Setup:
# ------
#
# To run this, you should read the setup guide:
# https://github.com/we-promise/sure/blob/main/docs/hosting/docker.md
#
# Troubleshooting:
# If you run into problems, you should open a Discussion here:
# https://github.com/we-promise/sure/discussions/categories/general
#
x-db-env: &a1
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB:-sure_production}
x-rails-env: &a2
  <<: *a1
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: db
  DB_PORT: 5432
  REDIS_URL: redis://redis:6379/1
  OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
services:
  web:
    image: ghcr.io/we-promise/sure:stable
    volumes:
      - /opt/stacks/sure:/rails/storage
    ports:
      - ${PORT:-30007}:3000
    restart: unless-stopped
    environment:
      <<: *a2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - sure_net
  worker:
    image: ghcr.io/we-promise/sure:stable
    command: bundle exec sidekiq
    volumes:
      - /opt/stacks/sure:/rails/storage
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      <<: *a2
    networks:
      - sure_net
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /opt/stacks/sure/postgres:/var/lib/postgresql/data
    environment:
      <<: *a1
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sure_net
  backup:
    profiles:
      - backup
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    volumes:
      - /opt/stacks/sure/backups:/backups
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-sure_production}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    depends_on:
      - db
    networks:
      - sure_net
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - /opt/stacks/sure/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sure_net
networks:
  sure_net:
    driver: bridge
