services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-media
    env_file:
      - .env
    environment:
      ALLOWED_HOSTS: ${HOST}:30000,homepage.local,localhost:3000 # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
    ports:
      - 30000:3000
    volumes:
      - ./config:/app/config
      #- /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
networks: {}
