# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# Homepage Address: http://{{HOMEPAGE_VAR_MY_IP}}:3000
- Media Stack:
    - SABnzbd:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:8585
        description: SABnzbd downloader
        icon: sabnzbd
        widget:
          type: sabnzbd
          url: http://{{HOMEPAGE_VAR_MY_IP}}:8585
          key: ${SABNZBD_API_KEY}

    - Sonarr:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:8989
        description: Sonarr TV manager
        icon: sonarr
        widget:
          type: sonarr
          url: http://{{HOMEPAGE_VAR_MY_IP}}:8989
          key: ${SONARR_API_KEY}

    - Radarr:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:7878
        description: Radarr movie manager
        icon: radarr
        widget:
          type: radarr
          url: http://{{HOMEPAGE_VAR_MY_IP}}:7878
          key: ${RADARR_API_KEY}

    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:9696
        description: Prowlarr indexer manager
        icon: prowlarr
        widget:
          type: prowlarr
          url: http://{{HOMEPAGE_VAR_MY_IP}}:9696
          key: ${PROWLARR_API_KEY}

    - Profilarr:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:6868
        description: Profilarr profile manager
        icon: mdi-chart-box

- Book Stack:
    - Calibre-web:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:8083
        description: Calibre-web library manager
        icon: calibre-web
        widget:
          type: calibreweb
          url: http://{{HOMEPAGE_VAR_MY_IP}}:8083
          username: ${CALIBREWEB_USERNAME}
          password: ${CALIBREWEB_PASSWORD}

    - Audiobookshelf:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:13378
        description: Audiobookshelf media server
        icon: audiobookshelf
        widget:
          type: audiobookshelf
          url: http://{{HOMEPAGE_VAR_MY_IP}}:13378
          key: ${AUDIOBOOKSHELF_KEY}

    - Komga:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:25600
        description: Komga comics server
        icon: komga
        widget:
          type: komga
          url: http://{{HOMEPAGE_VAR_MY_IP}}:25600
          username: ${KOMGA_USERNAME}
          password: ${KOMGA_PASSWORD}
          key: ${KOMGA_API_KEY}

- Book Aquisition:
    - Grimmory:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:6060
        description: Grimmory book management app
        icon: mdi-book-open-page-variant
    - Shelfmark:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:8084
        description: Sheflmark book management app
        icon: mdi-book-open-page-variant    

- Downloads:
    - qBittorrent:
        href: http://{{HOMEPAGE_VAR_MY_IP}}:21413
        description: qBittorrent torrent client
        icon: qbittorrent
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_MY_IP}}:21413
          username: ${QBITTORRENT_USERNAME}
          password: ${QBITTORRENT_PASSWORD}
