services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage-hermes
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_HOST}:3000,localhost:3000,homepage.local
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
    restart: unless-stopped