#sudo docker exec -it hermes-agent /bin/bash
#then hermes setup OR hermes model etc.

#Must generate password hash
#sudo docker exec -it hermes-agent bash
#python -c "from plugins.dashboard_auth.basic import hash_password; print(hash_password('your-password'))"
#Then add to hermes config.yaml and restart hermes
# dashboard:
#  bind: 0.0.0.0
#  basic_auth:
#    username: joseph
#    password_hash: "<paste-your-hash-here>"

services:
  hermes-agent:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-agent
    #command: dashboard --host 0.0.0.0 --port 9119
    command: gateway run
    ports:
      - 127.0.0.1:8642:8642
      - 9119:9119
    volumes:
      - /opt/stacks/hermes/agent:/home/hermes/.hermes
      - hermes-agent-src:/opt/hermes
      - /opt/stacks:/stacks
      - hermes-data:/opt/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HERMES_DASHBOARD=1
      - HERMES_HOME=/home/hermes/.hermes
      - HERMES_UID=1000
      - HERMES_GID=1000
    restart: unless-stopped
    networks:
      - hermes-net
  #Hermes Webui
  hermes-webui:
    image: ghcr.io/nesquena/hermes-webui:latest
    container_name: hermes-webui
    depends_on:
      - hermes-agent
    ports:
      - 8787:8787
    volumes:
      - /opt/stacks/hermes/agent:/home/hermeswebui/.hermes
      - hermes-agent-src:/home/hermeswebui/.hermes/hermes-agent:ro
      - /opt/stacks/hermes/agent/workspace:/workspace
    environment:
      - HERMES_WEBUI_PASSWORD=
      - HERMES_WEBUI_HOST=0.0.0.0
      - HERMES_WEBUI_PORT=8787
      - HERMES_WEBUI_STATE_DIR=/home/hermeswebui/.hermes/webui
      - HERMES_API_URL=http://hermes-agent:8642
      - WANTED_UID=1000
      - WANTED_GID=1000
    restart: unless-stopped
    networks:
      - hermes-net
networks:
  hermes-net:
    driver: bridge
volumes:
  hermes-agent-src: null
  hermes-data: null
