services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    ports:
      - 3099:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/dockhand:/app/data
      - /opt/stacks:/stacks
    environment:
      - DATA_DIR=/opt/stacks 
volumes:
  dockhand_data: null
networks: {}
