services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    volumes:
      - ./sabnzbd:/config
      - ${SHAREROOT}/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8585:8080
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./sonarr:/config
      - ${SHAREROOT}/TV:/TV
      - ${SHAREROOT}/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./radarr:/config
      - ${SHAREROOT}/Movies:/movies
      - ${SHAREROOT}/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 7878:7878
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./prowlarr:/config
      - ${SHAREROOT}:/Storage
      - ${SHAREROOT}/Downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    volumes:
      - ./profilarr:/config
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 6868:6868
    restart: unless-stopped
networks: {}
